// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyxMi0L1H36kDfO_GH4w1YfKSmuBJ36g',
    appId: '1:188327902009:web:1ac37bd7216d2c942246e8',
    messagingSenderId: '188327902009',
    projectId: 'greenmind-ai-497c9',
    authDomain: 'greenmind-ai-497c9.firebaseapp.com',
    storageBucket: 'greenmind-ai-497c9.firebasestorage.app',
    measurementId: 'G-Y7VSHR4HQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA873NJTCeqOY8vdIxRJvO-TMiS5mmj2KM',
    appId: '1:188327902009:android:83c708b586ca0aeb2246e8',
    messagingSenderId: '188327902009',
    projectId: 'greenmind-ai-497c9',
    storageBucket: 'greenmind-ai-497c9.firebasestorage.app',
  );
}
